---
abstract: 'Simplify digesting the same content with multiple digesters.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::Builder: '0'
  Test::More: '0.89'
  Test::Needs: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DigestX-Multi
provides:
  DigestX::Multi:
    file: lib/DigestX/Multi.pm
    version: '0.001000'
requires:
  Carp: '0'
  MIME::Base64: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/DigestX-Multi/issues
  homepage: https://github.com/kentnl/DigestX-Multi
  repository: https://github.com/kentnl/DigestX-Multi.git
version: '0.001000'
